let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Zebra Straits",
    price: 450,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/IMG_20220803_1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Konza",
    price: 1000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/IMG_20220803_2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Salambo",
    price: 1250,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/IMG_20220803_3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Ritual Somes",
    price: 1300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/IMG_20220803_4.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Mr Speaker",
    price: 2505,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/IMG_20220803_5.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Queen Tiriba",
    price: 2000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/IMG_20220803_6.jpg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Sangoma",
    price: 1050,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/IMG_20220803_7.jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Swan Diva",
    price: 1415,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/IMG_20220803_8.jpg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Tiribala",
    price: 850,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/IMG_20220803_9.jpg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Obongita",
    price: 1920,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/IMG_20220803_10.jpg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "Royal Pain",
    price: 1350,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/IMG_20220803_11.jpg",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Giraffe Wheels",
    price: 1550,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/IMG_20220803_12.jpg",
  },
];
